#!/bin/bash

cp-rotate() {
    if ! [ -d "$pwd/best" ] ;
    then
        mkdir "$pwd/best"
    fi
    convert -rotate 90 "$pwd/$img" "$pwd/best/${img%%.*}_r.jpg"
}

cp-normal() {
    if ! [ -d "$pwd/best" ] ;
    then
        mkdir "$pwd/best"
    fi
    cp "$pwd/$img" "$pwd/best/"
}

pwd="$(pwd)"
img="$(cat)"
echo $pwd
case $1 in
    "r" ) cp-rotate ;;
    "n" ) cp-normal ;;
    * ) echo "unknown: $1" ;;
esac
